/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Contenido;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author hquen
 */
public class InicioP extends javax.swing.JFrame {

    /**
     * Creates new form InicioP
     */
    public InicioP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new fondoPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        teo1 = new javax.swing.JButton();
        teo2 = new javax.swing.JButton();
        teo3 = new javax.swing.JButton();
        teo4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        teo5 = new javax.swing.JButton();
        teo6 = new javax.swing.JButton();
        teo7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Proyecto Estadistica 1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 24, -1, -1));

        jPanel2.setOpaque(false);

        teo1.setBackground(new java.awt.Color(153, 102, 0));
        teo1.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        teo1.setText("Teorema 1");
        teo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teo1ActionPerformed(evt);
            }
        });

        teo2.setText("Teorema 2");
        teo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teo2ActionPerformed(evt);
            }
        });

        teo3.setText("Teorema 3");
        teo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teo3ActionPerformed(evt);
            }
        });

        teo4.setText("Teorema 4");
        teo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teo4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teo1)
                    .addComponent(teo2)
                    .addComponent(teo3)
                    .addComponent(teo4))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(teo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teo4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, 130));

        jPanel3.setOpaque(false);

        teo5.setText("Teorema 5");
        teo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teo5ActionPerformed(evt);
            }
        });

        teo6.setText("Teorema 6");
        teo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teo6ActionPerformed(evt);
            }
        });

        teo7.setText("Teorema 7");
        teo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teo7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teo5)
                    .addComponent(teo6)
                    .addComponent(teo7))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(teo5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teo6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teo7)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, 120, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 /////////////////////////////////////
    class fondoPanel extends JPanel {
    Image imagen;
    public void paint(Graphics i){
     imagen = new ImageIcon(getClass().getResource("/imagenes/fondoA.gif")).getImage();
    i.drawImage(imagen,0,0,getWidth(),getHeight(),this);  setOpaque(false);  //getWidth() y getHeigth() adopta el tamaño del panel
   super.paint(i); //pasa parametro i de la clase padre paint
    } 
    }    
    fondoPanel fondo =new fondoPanel(); //sirve para editar desde el panel de diseño 
    /////////////////////////////////////
     // esta funcion ajusta imagen y permite colocar en varios label
    ImageIcon imagen;String ruta; Icon icono;
    private void scImagen(JLabel lbl, String ruta){
    this.imagen = new ImageIcon(ruta);
    this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(),Image.SCALE_DEFAULT)); 
    lbl.setIcon(this.icono);
    this.repaint();
    }
    ////////////////////////////////////
    private void teo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teo1ActionPerformed
       Teorema1 frame1 = new Teorema1();
       frame1.setVisible(true);
       dispose();
    }//GEN-LAST:event_teo1ActionPerformed

    private void teo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teo2ActionPerformed
      Teorema2 frame2 = new Teorema2();
       frame2.setVisible(true);
       dispose();  
    }//GEN-LAST:event_teo2ActionPerformed

    private void teo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teo3ActionPerformed
Teorema3 frame3 = new Teorema3();
       frame3.setVisible(true);
       dispose();    }//GEN-LAST:event_teo3ActionPerformed

    private void teo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teo4ActionPerformed
       Teorema4 frame4 = new Teorema4();
       frame4.setVisible(true);
       dispose();
    }//GEN-LAST:event_teo4ActionPerformed

    private void teo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teo5ActionPerformed
Teorema5 frame5 = new Teorema5();
       frame5.setVisible(true);
       dispose();    }//GEN-LAST:event_teo5ActionPerformed

    private void teo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teo6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teo6ActionPerformed

    private void teo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teo7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teo7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton teo1;
    private javax.swing.JButton teo2;
    private javax.swing.JButton teo3;
    private javax.swing.JButton teo4;
    private javax.swing.JButton teo5;
    private javax.swing.JButton teo6;
    private javax.swing.JButton teo7;
    // End of variables declaration//GEN-END:variables
}
